@FitnessTracker.Api_HostAddress = http://localhost:5165

POST {{FitnessTracker_Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Danilo",
  "lastName": "Test",
  "email": "danilo@example.com",
  "password": "Trening123"
}

###
